// Auto-generated by: supabase gen types typescript --project-id <project-id>
// Run this command after applying migrations to keep types in sync.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type Database = {
  public: {
    Tables: Record<string, never>
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: Record<string, never>
  }
}
